export const runtimeConfig = {
  statusItem: {
    id: "plume.languageVersion",
    name: "Plume Language Version",
    priority: 1000,
    text: "%s %s",
    command: "workbench.action.editor.changeLanguageMode",
  },
  customStyles: {
    loaderId: "be5invis.vscode-custom-css",
    section: "vscode_custom_css",
    importsKey: "imports",
    plumeImportPattern: /\/plume\.plume-themes-[^/]+\/dist\/plume\.css$/,
    workbenchPage: ["out", "vs", "code", "electron-browser", "workbench", "workbench.html"],
    applyCommand: "extension.updateCustomCSS",
    prompt: "Plume styles changed. Apply them now?",
    action: "Apply Styles",
  },
  typeScript: {
    languages: ["typescript", "typescriptreact"],
    workspaceManifest: ["node_modules", "typescript", "package.json"],
    bundledManifest: ["extensions", "node_modules", "typescript", "package.json"],
  },
  versionPattern: /(?<version>\d+(?:\.\d+)+)/,
  versionCommands: {
    php: { binary: "php", args: ["-r", "echo PHP_VERSION;"] },
    javascript: { binary: "node", args: ["--version"] },
    javascriptreact: { binary: "node", args: ["--version"] },
    python: { binary: "python3", args: ["--version"] },
    go: { binary: "go", args: ["version"] },
    rust: { binary: "rustc", args: ["--version"] },
    java: { binary: "java", args: ["--version"] },
    ruby: { binary: "ruby", args: ["--version"] },
    dart: { binary: "dart", args: ["--version"] },
    swift: { binary: "swift", args: ["--version"], pattern: /Swift version (?<version>\d+(?:\.\d+)+)/ },
    c: { binary: "clang", args: ["--version"] },
    cpp: { binary: "clang", args: ["--version"] },
    "objective-c": { binary: "clang", args: ["--version"] },
    shellscript: { binary: "bash", args: ["--version"] },
  },
} as const;
